version: "3.5"
services: 
    # sql:
    #     image: mcr.microsoft.com/mssql/server:2017-latest
    #     container_name: sql
    #     ports: 
    #         - 1433:1433
    #     environment: 
    #         - ACCEPT_EULA=Y
    #         - SA_PASSWORD=Secure@001
    #     volumes: 
    #         - sql1data:/var/opt/mssql
    #     networks: 
    #         - microservice

    db:
        image: postgres
        container_name: pgsql
        ports: 
            - 5432:5432
        environment: 
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=Secure@001
        volumes: 
            - sql1data:/var/opt/mssql
        networks: 
            - microservice
    
    web:
        image: employee-microservice
        container_name: micregs
        build: 
            context: .
            dockerfile: Registration/Dockerfile
        environment: 
            - ASPNETCORE_URLS=http://+:5000
            - ASPNETCORE_ENVIRONMENT=Production
            - PG_SERVER=db
            - PG_SERVER_PORT=5432
            - PG_DATABASE=Employee
            - PG_USERNAME=postgres
            - PG_PASSWORD=Secure@001
        ports: 
            - 5000:5000
        depends_on: 
            - db
        restart: on-failure
        networks: 
            - microservice
    
    spa:
        image: employee-spa
        container_name: emp-spa
        build: 
            context: .
            dockerfile: SPA/Dockerfile
        ports:
            - 8080:80
        networks: 
            - microservice

volumes: 
    sql1data:

networks: 
    microservice:
        name: microservice