version: "3.5"
services: 
    # sql:
    #     image: mcr.microsoft.com/mssql/server:2017-latest
    #     container_name: sql
    #     ports: 
    #         - 1433:1433
    #     environment: 
    #         - ACCEPT_EULA=Y
    #         - SA_PASSWORD=Secure@001
    #     volumes: 
    #         - sql1data:/var/opt/mssql
    #     networks: 
    #         - microservice

    db:
        image: postgres
        container_name: pgsql
        ports: 
            - 5432:5432
        environment: 
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=Secure@001
        volumes: 
            - sql1data:/var/opt/mssql
        networks: 
            - microservice
    
    redis:
        image: redis
        container_name: redis
        ports:
            - 6379:6379
        volumes: 
            - redis:/data
        networks:
            - microservice

    cache:
        image: cache-microservice
        container_name: cache-svc
        build: 
            context: .
            dockerfile: CacheService/Dockerfile
        environment: 
            - ASPNETCORE_URLS=http://+:5001
            - ASPNETCORE_ENVIRONMENT=Production
            - PG_SERVER=db
            - PG_SERVER_PORT=5432
            - PG_DATABASE=CacheData
            - PG_USERNAME=postgres
            - PG_PASSWORD=Secure@001
            - API_PATH_BASE=cache
            - CACHE_TIMEOUT=600
        ports: 
            - 5001:5001
        depends_on: 
            - db
        restart: on-failure
        networks: 
            - microservice
    
    web:
        image: employee-microservice
        container_name: employee-svc
        build: 
            context: .
            dockerfile: Registration/Dockerfile
        environment: 
            - ASPNETCORE_URLS=http://+:5000
            - ASPNETCORE_ENVIRONMENT=Production
            - PG_SERVER=db
            - PG_SERVER_PORT=5432
            - PG_DATABASE=Employee
            - PG_USERNAME=postgres
            - PG_PASSWORD=Secure@001
            - API_PATH_BASE=employee
            - CACHE_SERVICE_URL=http://cache:5001/cache/api
        ports: 
            - 5000:5000
        depends_on: 
            - db
            - cache
        restart: on-failure
        networks: 
            - microservice
    
    spa:
        image: employee-spa
        container_name: emp-spa
        build: 
            context: .
            dockerfile: SPA/Dockerfile
        environment:
            - BASE_API_URL=http://localhost:5000/employee/api/
        ports:
            - 8080:80
        networks: 
            - microservice

volumes: 
    sql1data:
    redis:

networks: 
    microservice:
        name: microservice