apiVersion: apps/v1
kind: Deployment
metadata:
    name: server-deployment
spec:
    replicas: 3
    selector:
        matchLabels:
            component: server
    template:
        metadata:
            labels:
                component: server
        spec:
            containers:
                - name: server
                  image: nakash2050/employee-microservice
                  ports:
                    - containerPort: 5000
                  env:
                    - name: ASPNETCORE_URLS
                      value: http://+:5000
                    - name: ASPNETCORE_ENVIRONMENT
                      value: Production
                    - name: API_PATH_BASE
                      value: employee-api
                    - name: PG_SERVER
                      value: postgres-cluster-ip-service
                    - name: PG_SERVER_PORT
                      value: '5432'
                    - name: PG_DATABASE
                      value: Employee
                    - name: PG_USERNAME
                      value: postgres
                    - name: PG_PASSWORD
                      valueFrom:
                        secretKeyRef:
                            name: pgpassword
                            key: PG_PASSWORD