apiVersion: apps/v1
kind: Deployment
metadata:
    name: client-deployment
spec:
    replicas: 1
    selector:
        matchLabels:
            component: web
    template:
        metadata:
            labels:
                component: web
        spec:
            containers:
                - name: client
                  image: nakash2050/employee-spa
                  ports:
                    - containerPort: 80
                  env:
                    - name: BASE_API_URL
                      value: http://localhost/employee-api/api/